base-syntax dz
TatianaZalyalova/base-syntax pull request #1
Opened 2021-08-13 14:49 UTC by TatianaZalyalova

2021-08-17 10:01 UTC, vasiliev-alexey commented
1. В репозитории находятся паки котрых там быть не должно - советую почитать  https://github.com/elsewhencode/project-guidelines/blob/master/README-ru.md#some-git-rules

2021-08-17 10:51 UTC, vasiliev-alexey requested changes
В целом - задание решено, но в продуктив я бы такй код не пустил.
Прослушай еще раз лекцию по организацию кода, прочитай гайд https://github.com/elsewhencode/project-guidelines/blob/master/README-ru.md

2021-08-17 10:51 UTC, vasiliev-alexey commented on 1/script.js
> +  if (number.length === 3) {
А если введут не числа ?  Стоит добавить проверку на NaN

2021-08-17 10:51 UTC, vasiliev-alexey commented on 1/script.js
> +export function getSum(a, b) {
Имя функции не отвечает логике ее работы

2021-08-17 10:51 UTC, vasiliev-alexey commented on 1/script.test.js
> +    console.log = jest.fn();
Мокаем глобальные функции - освобождаем после теста -  https://jestjs.io/ru/docs/25.x/api .

beforeEach afterEach

2021-08-17 10:51 UTC, vasiliev-alexey commented on 1/script.test.js
> +  });
В каждом тесткейсе много дубоирующегося кода посмотри на https://jestjs.io/docs/api#testeachtablename-fn-timeout

2021-08-17 10:51 UTC, vasiliev-alexey commented on 6/script.js
> +}
А если будет  @@@@  - будет ли это словом ?

2021-08-17 10:51 UTC, vasiliev-alexey commented on 7/script.test.js
> +  form.submit();
Зачем 2 раза ?

2021-08-17 10:51 UTC, vasiliev-alexey commented on 7/script.test.js
> +  form.submit();
Код надо писать так, чтобы его было приятно читать - разбивать его на семантические абзацы. Компьютеру все равено , а глазу и проверяющему приятно

https://github.com/elsewhencode/project-guidelines/blob/master/README-ru.md#code-style-check

2021-08-17 10:51 UTC, vasiliev-alexey commented on 8/script.js
> +export function kenUserYounger(date1, date2) {
имя  функции ну явно ни о чем не говорит , как и имена параметров - пиши не для себя, а для  друзей

2021-08-17 10:51 UTC, vasiliev-alexey commented on 8/script.test.js
> +  it("circleInSqar 15.06.2001 15.06.2001", () => {
имена тестов должны быть уникальны в перделах одного тест сьюта

2021-08-17 10:51 UTC, vasiliev-alexey commented on 9/script.test.js
> +describe("kenUserYounger", () => {
имя сьюта явно не то

2021-08-17 10:51 UTC, vasiliev-alexey commented on .eslintrc.js
> +    "no-param-reassign": [2, { props: false }],
а зачем off то - хорошее же правило

2021-08-30 18:39 UTC, AntiHero commented on package.json
>    "dependencies": {
перенести зависимости для разработки в devDep

2021-08-30 18:39 UTC, AntiHero commented on 7/script.test.js
> +  expect(button.disabled).toBe(true);
желательно разбить на три отдельных теста

2021-08-30 18:39 UTC, AntiHero commented on 3/script.test.js
> +    expect(console.log).toHaveBeenCalledWith("7 * 9 = 63");
`.toHaveBeenLastCalledWith`
`.toHaveBeenNthCalledWith`

2021-08-30 18:39 UTC, AntiHero commented on package.json
> +    "lint-staged": "^11.1.2",
поправить sanity-check.yml

2021-08-31 19:39 UTC, merged